copy2esphome/ulanzi-easy.yaml
Had some trouble with the default configuration options when attempting to test.
The reference tag can probably be changed if there is a release tag.  I haven't tested a running version yet, but this will pass validation.
=> Updated to pass validation

README.md
original link 404ed (in a nice way!), but I think I found the new URL
=> Update link to pixel it

copy2esphome/ulanzi-easy.yaml
=> Use Matrix Clock Fonts in easy example

CHANGELOG.md, README.md, components/ehmtxv2/EHMTX.cpp
Image URL was wrong as well as the mateine font name.
=> Fix some documentation typos

README.md
In #73 the default fonts changed in the example file. This MR updates the README and mentions the new fonts.
=> mention new fonts in readme

README.md, components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_queue.cpp
Fix for: https://github.com/lubeda/EspHoMaTriXv2/issues/89#issuecomment-1750970279
=> 2023.9.1: Fix for Unicode chars in Info text

components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_queue.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/89#issuecomment-1751777404
=> 2023.9.1: Fix for Korean symbols for the day of the week, one symbol is a day.

README.md, components/ehmtxv2/EHMTX_queue.cpp
=> 2023.9.1: Add mode 5 for day, to the center, without leading 0

README.md, components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/__init__.py
https://github.com/lubeda/EspHoMaTriXv2/issues/103
=> 2023.9.1-103: Night Mode

README.md, components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_queue.cpp
FEATURE REQUEST - https://github.com/lubeda/EspHoMaTriXv2/issues/90#issuecomment-1737217802
=> 2023.9.1-90: Add Graph with icon screen

README.md, components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_queue.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/91#issuecomment-1759398401
=> 2023.9.1-91: Add set_progressbar_color

README.md
Just some small corrections in the readme. Otherwhise a very nice project.
=> Spellcheck README

components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h
https://github.com/lubeda/EspHoMaTriXv2/issues/134
=> 2023.9.1-134: Add transition to brightness

components/ehmtxv2/EHMTX.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/129
=> 2023.9.1-129: Turn off blend_step at low brightness < 50

README.md, components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_queue.cpp, components/ehmtxv2/__init__.py
https://github.com/lubeda/EspHoMaTriXv2/issues/139
=> 2023.9.1: Add Bitmap Stack screen

wiki-samples/type1.yaml
https://github.com/lubeda/EspHoMaTriXv2/issues/155
=> 2023.9.1: Fix in Wiki samples (type 1)

components/ehmtxv2/EHMTX.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/152
=> 2023.9.1-152: last_time - actual time

components/ehmtxv2/EHMTX.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/152
=> 2023.9.1-152: find_oldest_queue_element fix

components/ehmtxv2/EHMTX.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/133
=> 2023.9.1-133: Fix for Screens re-starts and showing twice if 'force_screen' send

README.md, components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_queue.cpp, components/ehmtxv2/__init__.py
https://github.com/lubeda/EspHoMaTriXv2/issues/149
=> 2023.9.1-149: Add icon prognosis screen

README.md, components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_queue.cpp, components/ehmtxv2/__init__.py
Adds the ability to enable screen switching using vertical scrolling.
```
ehmtxv2:
id: rgb8x32
...
vertical_scroll: true
...
```
=> 2023.9.1: Vertical scroll of screen

components/ehmtxv2/EHMTX_queue.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/169
=> 2023.9.1-169: Fix Rainbow text color in MODE_RAINBOW_ICON_TEXT_SCREEN

README.md, components/ehmtxv2/__init__.py
https://github.com/lubeda/EspHoMaTriXv2/issues/167
=> 2023.9.1-167: Icons cache

README.md, components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_queue.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/175
=> 2023.9.1: Add Rainbow Alert Screen

components/ehmtxv2/EHMTX_queue.cpp
Day Mode 5 and Day < 10
If Weekday array == 7
=> 2023.9.1: Move icon text to right in Icon to 9 mode 3

components/ehmtxv2/__init__.py
https://github.com/lubeda/EspHoMaTriXv2/issues/190#issuecomment-1915365583
=> 2024.1.0: Fix for `on_show_display` `on_night_mode` `on_next_screen` triggers

components/ehmtxv2/EHMTX.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/222
=> 2024.4.0: Fix for display Off

components/ehmtxv2/EHMTX.h, components/ehmtxv2/EHMTX_icons.cpp, components/ehmtxv2/__init__.py
Fixes https://github.com/lubeda/EspHoMaTriXv2/issues/275
Feel free to create a new version and re-target the PR to it as I only can target `2024.12.1` :)
=> Required Animation changes for ESPHome 2025.2.0

components/ehmtxv2/EHMTX.cpp, components/ehmtxv2/EHMTX.h
https://github.com/lubeda/EspHoMaTriXv2/issues/291
=> 2025.5.3: bugfix for `del_screen` does not yet work with icon names containing a `screen_id`

README.md
https://github.com/lubeda/EspHoMaTriXv2/issues/291#issuecomment-2930366797
=> Doc: Add examples for `screen_id`

components/ehmtxv2/EHMTX_queue.cpp
messed up versions
Reverts lubeda/EspHoMaTriXv2#296
=> Revert "2025.5.3: Extend `Screen Clipping`"
