lubeda/EspHoMaTriXv2

- copy2esphome/EHMTX_easy_delete.yaml
- copy2esphome/EHMTX_easy_hide.yaml
- copy2esphome/EHMTX_easy_show.yaml
- copy2esphome/EHMTX_easy_state.yaml
- copy2esphome/EHMTX_extended_state.yaml
- copy2esphome/ulanzi-easy.yaml
Added a Manufacturer (Ulanzi) and Model (EHMTXv2) within the ESPHome Project Name 
Added filtering on the blueprints to only show EspHome devices with model of EHMTXv2 
Also made device name selection consistent on all blueprints
> Improve blueprint device selection

- components/ehmtxv2/EHMTX.h
Fixes the RealTimeClock compile error because of movement of time functions since esphome 2023.6.1.
Breaking change PR: https://github.com/esphome/esphome/pull/4926
> Fix compile error for esphome version greater than 2023.6.1

- copy2esphome/EHMTX_easy_state.yaml
This PR simply adds a variable for the input value _use_colors_ to be used in the if/then check later on. Otherwise the input value will be ignored, resulting in the condition to render true and only the default color will be used regardless of the setting.
> fix value dependent color usage

- README.md
- copy2esphome/EHMTX_extended_state.yaml
- copy2esphome/ulanzi-easy.yaml
- wiki/fonts.md
Hey, hey.  Had some issues with the file names and hyphens and MatrixClockFonts was a mouthful so...
> Matrix fonts renamed

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
**2023.9.1**: Screen ID, Progress screen, Icon with Text
* Added the ability to specify a screen ID - `icon_name|screen_id`
* Added icon and date output screen - `icon_date(iconname, lifetime, screen_time, default_font, r, g, b)`
* If pass a screen identifier with the value `[day, weekday]` like `icon_name|day`, and a backing icon to `icon_clock` or `icon_date`, it will display text.
* Added a screen with the ability to display a progress bar, progress value (-100..100) - `icon_screen_progress(iconname, text, progress, lifetime, screen_time, default_font, r, g, b)`
Should solve the issues: https://github.com/lubeda/EspHoMaTriXv2/issues/83 https://github.com/lubeda/EspHoMaTriXv2/issues/91 https://github.com/lubeda/EspHoMaTriXv2/issues/92
> 2023.9.1: Screen ID, Progress screen, Icon with Text

- components/ehmtxv2/EHMTX.cpp
```
In file included from src/esphome/components/sensor/sensor.h:3,
from src/esphome/components/adc/adc_sensor.h:6,
from src/esphome.h:3,
from src/esphome/components/ehmtxv2/EHMTX.cpp:1:
src/esphome/components/ehmtxv2/EHMTX.cpp: In member function 'void esphome::EHMTX::show_gauge(int, int, int, int, int, int, int)':
src/esphome/components/ehmtxv2/EHMTX.cpp:267:21: error: format '%d' expects argument of type 'int', but argument 5 has type 'double' [-Werror=format=]
ESP_LOGD(TAG, "show_gauge 2 color %d", round(percent));
^~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
#define ESPHOME_LOG_FORMAT(format) format
^~~~~~
src/esphome/core/log.h:152:28: note: in expansion of macro 'esph_log_d'
#define ESP_LOGD(tag, ...) esph_log_d(tag, …
```
> Fix percent logging

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
The character count for weekdays could be moved to the `__init__.py` instead of before which iterated through the string just to count the characters... a permanent variable set is set during compile and then used instead.
Also, fixed some typos to do with Night Mode (in all files)... and a little one in the readme.
> Moved char count for weekdays to init & edit typos

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/117
> 2023.9.1-117: Add a pseudo icon - blank

- components/ehmtxv2/EHMTX.cpp
2023.9.1: Fix for screen_id when only iconname defined and iconname with `_` sign.
> 2023.9.1: Fix for screen_id when only iconname defined

- components/ehmtxv2/EHMTX.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/122#issuecomment-1783894845
> 2023.9.1: If lifetime = 0, then lifetime = screen time

- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
https://github.com/lubeda/EspHoMaTriXv2/pull/116#issuecomment-1774571035
> 2023.9.1-PR116: Move sbitmap to EHMTX::queue

- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
The first draft, while it doesn't work yet, in theory should solve the problem https://github.com/lubeda/EspHoMaTriXv2/issues/122
> 2023.9.1-122: Change timestamp to milliseconds

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
https://github.com/lubeda/EspHoMaTriXv2/issues/143
> 2023.9.1: Add text progress screen

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
In the dark, it is very difficult to tell the time of the week as you can only see the current streak of the day, but this way it will be clear what day it is in any light.
> 2023.9.1: Added accent for days of week

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
https://github.com/lubeda/EspHoMaTriXv2/issues/164
> 2023.9.1: Advanced clock

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
Extends the icon display on the clock screen and date screen by one line (9 pixels wide). 
Convenient for displaying the current date with a distance of one pixel between numbers, visual harmony. 
Mode 0 (default) - do not expand. 
Mode 1 - expand only on the clock screen. 
Mode 2 - expand only on the date screen. 
Mode 3 - expand on the screen with clock and on the screen with date.
> 2023.9.1: Expand Icon to 9 pixels

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
Advanced mode of Bitmap screen (MODE_BITMAP_SCREEN), allows the use of screen identifiers, which in turn makes it possible to display more than one Bitmap screen on the clock.
But it can also increase RAM consumption, each screen + 256 bytes.
> 2023.9.1: Add advanced Bitmap mode

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
Pseudo-icon `solid` - icon as square filled with solid color, see `set_solid_color`.
Pseudo-icon `calendar` - calendar icon with default white color, and header as color from `set_calendar_color`.
> 2023.9.1: Add pseudo icon - solid and calendar

- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
**Advanced mode of boot logo display**
Allows you to show a custom boot logo instead of the default animation when booting.
`advanced_boot` (optional, boolean, only on ESP32, Default: false) Enables advanced mode of boot logo display.
`boot_logo` (optional, string, only on ESP32): Mask defined as rgb565 array used to display boot logo, color is completely ignored, output depends on boot logo display mode.
`boot_mode` (optional, integer, only on ESP32, Default: 3) Mode of displaying boot logo, can take value from 0 to 3:
- 0 - Display boot_logo in white color
- 1 - Display boot_logo in white color, the mask appears from the center to the sides.
- 2 - Display boot_logo with rainbow color
- 3 - Display boot_logo in rainbow color, the mask appears from the center to the sides
Mode 3 is best …
> 2024.1.0: Advanced Boot Logo

- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/__init__.py
Changes to the discussion in the topic https://github.com/lubeda/EspHoMaTriXv2/pull/191
> 2024.1.0: Simplifying the Advanced boot logo

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/__init__.py
aka `True starship astronavigator modes`
Each element of the image mask array can take values from 0 to 255 (if the value is greater than 255, it is automatically reset to 255). Each pixel is output depending on the bit that is set in its value byte, for example:
- `1` - `10000000` - Will be displayed at every 1 cycle of the boot logo image output.
- `4` - `00100000` - Will be displayed at every 3 cycle of the boot logo image output.
- `255` - `11111111` - Will be displayed at each cycle of the boot logo image output.
> 2024.1.0: Add Boot logo mode 6 and 7 - pseudo animation

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
In advanced clock mode, the date separator will be displayed with the color of the clock separator.
> 2024.1.0: Advanced clock - draw date

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
Reverts lubeda/EspHoMaTriXv2#197
Your sample does not work!
```
Compiling .pioenvs/m5mic/src/main.cpp.o
<unicode string>: In lambda function:
<unicode string>:173:16: error: 'class esphome::EHMTX' has no member named 'set_clock_infotext_color'; did you mean 'set_infotext_color'?
<unicode string>:174:16: error: 'class esphome::EHMTX' has no member named 'set_adv_clock_color'; did you mean 'set_clock_color'?
<unicode string>:177:16: error: 'class esphome::EHMTX' has no member named 'set_date_infotext_color'; did you mean 'set_infotext_color'?
*** [.pioenvs/m5mic/src/main.cpp.o] Error 1
```
> Revert "2024.1.0: Advanced clock - draw date"

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
Reverts lubeda/EspHoMaTriXv2#198
Are you sure you haven't forgotten about **advanced_clock: true** ?
> Revert "Revert "2024.1.0: Advanced clock - draw date""

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
Fix HUE Rainbow color loop
Add `rainbow_shimmer` (optional, boolean): If true, enables color shimmer when displaying text in rainbow modes.
> 2024.3.0: Add Rainbow Shimmer

- components/ehmtxv2/EHMTX.h
Fixes wired brightness issues at boot because of uninitialized brightness_ variable.
With this change the clock dimms to the yaml configured target brightness (or which was set via code).
> Fix uninitialized brighntess_ variable

- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/__init__.py
https://github.com/lubeda/EspHoMaTriXv2/issues/225
> 2024.4.0: Fix for Night loop

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
Added the ability to specify the required brightness when displaying a given BITMAP screen. 
Works only in advanced BITMAP mode. 
```
icon: [....]|screen_id# - Brightness 240 (Default) 
icon: [....]|screen_id#200 - Brightness 200
```
> 2024.4.1: Specifying the brightness for the BITMAP screen

- README.md
- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_queue.cpp
- components/ehmtxv2/__init__.py
**multicolor_text** (optional, boolean): If true, enables text multi color support when displaying text.
Example:
```Yaml
ehmtxv2:
id: rgb8x32
...
multicolor_text: true
```
```Yaml
service: esphome.ulanzi_text_screen
data:
default_font: true
text: "Test Test #00FF00Test #FF0000Test #0000FFTest"
lifetime: 2
screen_time: 10
r: 255
g: 255
b: 255
```
Shows text in different colors, `Test Test` in the default color `#FFFFFF` (r: 255, g:255, b: 255), followed by `Test` in green `#00FF00`, then `Test` in red `#FF0000` and finally `Test` in blue `#0000FF`.
> 2024.6.1: Add `multicolor text` support

- components/ehmtxv2/__init__.py
Some sites set headers incorrectly, and then when a file is changed, it loads from the cache, not the new one.
This solution should fix this problem.
> 2024.6.1: Turn off cache when download

- .github/workflows/main.yml
- install/ulanzi-easy.yaml
- tests/ulanzi-test.yaml
https://github.com/lubeda/EspHoMaTriXv2/issues/240
> ESPhome 2024.6.1 Breaking Change: Update YAML File for OTA Fix

- install/ulanzi-easy.yaml
This MR mostly fixes the default install config file, but also removes trailing whitespaces and updates version
Should fix https://github.com/lubeda/EspHoMaTriXv2/issues/258
I also included the fix from https://github.com/lubeda/EspHoMaTriXv2/issues/248#issuecomment-2435888083
> update base config: fix typo, add ignore_efuse_custom_mac, remove trailing spaces, update version

- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
- components/ehmtxv2/EHMTX_icons.cpp
- components/ehmtxv2/EHMTX_queue.cpp
Building with a configuration file for esp-idf like
```yaml
esp32:
board: esp32-s3-devkitc-1
variant: esp32s3
flash_size: 8MB
framework:
type: esp-idf
version: recommended
```
currently fails with errors like:
```
Building .pioenvs\test-esp-build\bootloader.bin
esptool.py v4.8.1.1
Creating esp32s3 image...
Merged 1 ELF section
Successfully created esp32s3 image.
Linking .pioenvs\test-esp-build\firmware.elf
.../.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/test-esp-build/src/esphome/components/ehmtxv2/EHMTX.cpp.o:(.literal._ZN7esphome3api15UserServiceBaseIJiiiiiiiEE28encode_list_service_responseEv[_ZN7esphome3api15UserServiceBaseIJiiiiiiiEE28encode_list_service_responseEv]+0x0): undefined reference …
```
> Replace usage of int with int32_t to built for both platforms arduino and esp-idf.

- components/ehmtxv2/EHMTX.h
Building for the combination esp-idf and esp32s3currently fails with errors like:
```
src/esphome/components/ehmtxv2/EHMTX.cpp:1602:61: error: 'F' was not declared in this scope
1602 |     ESP_LOGI(TAG, "status display %s", this->show_display ? F("on") : F("off"));
|                                                             ^
src/esphome/core/log.h:110:99: note: in definition of macro 'esph_log_i'
110 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
|                                                                                                   ^~~~~~~~~~~
src/esphome/components/ehmtxv2/EHMTX.cpp:1602:5: note: in expansion of macro 'ESP_LOGI'
1602 |     ESP_LOGI(TAG, "status display %s", this->show_display ? F("on") : …
```
> Added string formatting macro to build on esp-idf and esp32s3.

- components/ehmtxv2/EHMTX.cpp
- components/ehmtxv2/EHMTX.h
When all elements are expired and the queue is empty, new elements may be added through the *on_empty_queue* automation. The new elements are not shown directly, instead a blank screen is shown for 15 seconds.
Log output:
```
[10:53:57][C][EHMTXv2:3121]: EspHoMatriXv2 version: 2025.2.1
[10:53:57][C][EHMTXv2:3122]: Icons: 1 of 100
[10:53:57][C][EHMTXv2:3123]: Clock interval: 0 s
[10:53:57][C][EHMTXv2:3124]: Date format: %d/%m
[10:53:57][C][EHMTXv2:3125]: Time format: %H:%M
[10:53:57][C][EHMTXv2:3126]: Interval (ms) scroll: 80
[10:53:57][C][EHMTXv2:3129]: Show day of week
[10:53:57][C][EHMTXv2:3137]: Weekstart: Monday
[10:53:57][C][EHMTXv2:3138]: Weekdays: SOMODIMIDOFRSA Count: 14
[10:53:57][C][EHMTXv2:3139]: Display: On
[10:53:57][C][EHMTXv2:3140]: Night mode: Off …
```
> Avoid blank screen for 15 seconds after empty queue.

- install/ulanzi-easy.yaml
- tests/esp32-arduino.yaml
- tests/esp32-idf-features.yaml
- tests/esp32-idf.yaml
I just ran across this from a change in 2025.5.0: https://github.com/esphome/esphome/pull/8542 
> NOTE: a side-effect of this PR is that the default CPU frequency for Arduino becomes 160MHz, rather than the 240MHz value baked into the Arduino core. ESP-IDF default was already 160.
A breaking change note is [pending](https://github.com/esphome/esphome-docs/pull/5013) and wasn't obvious from the [original changelog](https://esphome.io/changelog/2025.5.0).  Running at ~67% speed, it seems to affect timings for things like `blend_steps` but is much more noticeable for some addressable lambda effects I've added. 
You can now also verify the setting through the [debug component](https://esphome.io/components/debug.html).
> Add the new cpu_frequency option to retain 240Mhz

- components/ehmtxv2/EHMTX.cpp
https://github.com/lubeda/EspHoMaTriXv2/issues/291#issuecomment-3020208452
> Fix `wildcard` bug for `del_screen` does not yet work with icon names containing a `screen_id`

- components/ehmtxv2/EHMTX.cpp
Changed to std::lerp function.
> Fixes compile error depending on deleted esphome lerp function
